var DATA = [
    {c:1,n:"Adrar",r:"Sud",t:1,lon:-0.29,lat:27.87},
    {c:2,n:"Chlef",r:"Ouest",t:1,lon:1.34,lat:36.17},
    {c:3,n:"Laghouat",r:"Sud",t:1,lon:2.86,lat:33.80},
    {c:4,n:"Oum El Bouaghi",r:"Est",t:1,lon:7.11,lat:35.87},
    {c:5,n:"Batna",r:"Est",t:1,lon:6.17,lat:35.56},
    {c:6,n:"Béjaïa",r:"Est",t:1,lon:5.08,lat:36.75},
    {c:7,n:"Biskra",r:"Est",t:1,lon:5.73,lat:34.85},
    {c:8,n:"Béchar",r:"Sud",t:1,lon:-2.22,lat:31.62},
    {c:9,n:"Blida",r:"Centre",t:1,lon:2.83,lat:36.47},
    {c:10,n:"Bouira",r:"Centre",t:1,lon:3.90,lat:36.38},
    {c:11,n:"Tamanrasset",r:"Sud",t:1,lon:5.53,lat:22.79},
    {c:12,n:"Tébessa",r:"Est",t:1,lon:8.12,lat:35.40},
    {c:13,n:"Tlemcen",r:"Ouest",t:1,lon:-1.31,lat:34.88},
    {c:14,n:"Tiaret",r:"Ouest",t:1,lon:1.32,lat:35.37},
    {c:15,n:"Tizi Ouzou",r:"Centre",t:1,lon:4.05,lat:36.72},
    {c:16,n:"Alger",r:"Centre",t:1,lon:3.06,lat:36.75},
    {c:17,n:"Djelfa",r:"Centre",t:1,lon:3.26,lat:34.67},
    {c:18,n:"Jijel",r:"Est",t:1,lon:5.77,lat:36.82},
    {c:19,n:"Sétif",r:"Est",t:1,lon:5.41,lat:36.19},
    {c:20,n:"Saïda",r:"Ouest",t:1,lon:0.15,lat:34.83},
    {c:21,n:"Skikda",r:"Est",t:1,lon:6.91,lat:36.88},
    {c:22,n:"Sidi Bel Abbès",r:"Ouest",t:1,lon:-0.63,lat:35.19},
    {c:23,n:"Annaba",r:"Est",t:1,lon:7.77,lat:36.90},
    {c:24,n:"Guelma",r:"Est",t:1,lon:7.43,lat:36.46},
    {c:25,n:"Constantine",r:"Est",t:1,lon:6.61,lat:36.37},
    {c:26,n:"Médéa",r:"Centre",t:1,lon:2.75,lat:36.26},
    {c:27,n:"Mostaganem",r:"Ouest",t:1,lon:0.09,lat:35.93},
    {c:28,n:"M'Sila",r:"Centre",t:1,lon:4.54,lat:35.70},
    {c:29,n:"Mascara",r:"Ouest",t:1,lon:0.14,lat:35.40},
    {c:30,n:"Ouargla",r:"Sud",t:1,lon:5.33,lat:31.95},
    {c:31,n:"Oran",r:"Ouest",t:1,lon:-0.63,lat:35.70},
    {c:32,n:"El Bayadh",r:"Ouest",t:1,lon:1.02,lat:33.68},
    {c:33,n:"Illizi",r:"Sud",t:1,lon:8.47,lat:26.50},
    {c:34,n:"Bordj Bou Arréridj",r:"Est",t:1,lon:4.76,lat:36.07},
    {c:35,n:"Boumerdès",r:"Centre",t:1,lon:3.48,lat:36.75},
    {c:36,n:"El Tarf",r:"Est",t:1,lon:8.31,lat:36.77},
    {c:37,n:"Tindouf",r:"Sud",t:1,lon:-8.14,lat:27.68},
    {c:38,n:"Tissemsilt",r:"Ouest",t:1,lon:1.81,lat:35.61},
    {c:39,n:"El Oued",r:"Sud",t:1,lon:6.87,lat:33.37},
    {c:40,n:"Khenchela",r:"Est",t:1,lon:7.14,lat:35.44},
    {c:41,n:"Souk Ahras",r:"Est",t:1,lon:7.95,lat:36.29},
    {c:42,n:"Tipaza",r:"Centre",t:1,lon:2.45,lat:36.59},
    {c:43,n:"Mila",r:"Est",t:1,lon:6.26,lat:36.45},
    {c:44,n:"Aïn Defla",r:"Centre",t:1,lon:1.97,lat:36.26},
    {c:45,n:"Naâma",r:"Ouest",t:1,lon:-0.31,lat:33.27},
    {c:46,n:"Aïn Témouchent",r:"Ouest",t:1,lon:-1.14,lat:35.30},
    {c:47,n:"Ghardaïa",r:"Sud",t:1,lon:3.67,lat:32.49},
    {c:48,n:"Relizane",r:"Ouest",t:1,lon:0.56,lat:35.74},
    {c:49,n:"Timimoun",r:"Sud",t:2,lon:0.23,lat:29.26},
    {c:50,n:"Bordj Badji Mokhtar",r:"Sud",t:2,lon:0.94,lat:21.33},
    {c:51,n:"Ouled Djellal",r:"Sud",t:2,lon:5.06,lat:34.42},
    {c:52,n:"Béni Abbès",r:"Sud",t:2,lon:-2.17,lat:30.13},
    {c:53,n:"In Salah",r:"Sud",t:2,lon:2.48,lat:27.19},
    {c:54,n:"In Guezzam",r:"Sud",t:2,lon:5.77,lat:19.57},
    {c:55,n:"Touggourt",r:"Sud",t:2,lon:6.06,lat:33.10},
    {c:56,n:"Djanet",r:"Sud",t:2,lon:9.48,lat:24.55},
    {c:57,n:"El M'Ghaier",r:"Sud",t:2,lon:5.93,lat:33.95},
    {c:58,n:"El Meniaa",r:"Sud",t:2,lon:2.88,lat:30.58},
    {c:59,n:"Aflou",r:"Hauts Plateaux",t:3,lon:2.10,lat:34.11},
    {c:60,n:"Barika",r:"Hauts Plateaux",t:3,lon:5.37,lat:35.38},
    {c:61,n:"El Kantara",r:"Hauts Plateaux",t:3,lon:5.71,lat:35.19},
    {c:62,n:"Bir El Ater",r:"Hauts Plateaux",t:3,lon:8.07,lat:35.02},
    {c:63,n:"El Aricha",r:"Hauts Plateaux",t:3,lon:-1.27,lat:34.50},
    {c:64,n:"Ksar Chellala",r:"Hauts Plateaux",t:3,lon:2.31,lat:35.20},
    {c:65,n:"Aïn Oussara",r:"Hauts Plateaux",t:3,lon:2.90,lat:35.45},
    {c:66,n:"Messaad",r:"Hauts Plateaux",t:3,lon:3.50,lat:34.15},
    {c:67,n:"Ksar El Boukhari",r:"Hauts Plateaux",t:3,lon:2.77,lat:35.86},
    {c:68,n:"Bou Saâda",r:"Hauts Plateaux",t:3,lon:4.19,lat:35.21},
    {c:69,n:"El Abiodh Sidi Cheikh",r:"Hauts Plateaux",t:3,lon:0.53,lat:32.89}
  ];

  var HOOKS = [
    [1,"Adrar","la plus grande wilaya du pays porte le tout premier code."],
    [2,"Chlef","juste après Adrar sur la liste, sur la côte à l'ouest d'Alger (ex-Al Asnam)."],
    [3,"Laghouat","porte du Sahara, à trois pas des Hauts Plateaux."],
    [4,"Oum El Bouaghi","carrefour discret de l'Est, au cœur du bloc 01–15."],
    [5,"Batna","au pied des Aurès — cinq wilaya, cinq grands massifs autour d'elle."],
    [6,"Béjaïa","le grand port de Kabylie."],
    [7,"Biskra","la porte du Sahara, célèbre pour ses palmeraies."],
    [8,"Béchar","loin à l'ouest du grand Sud."],
    [9,"Blida","la ville des roses, collée à Alger (16) mais numérotée bien avant elle."],
    [10,"Bouira","en Kabylie profonde, sur la route vers le Sud."],
    [11,"Tamanrasset","tout au sud, au cœur du Hoggar — deux \"1\" comme deux pics jumeaux."],
    [12,"Tébessa","à la frontière tunisienne, porte de l'Est."],
    [13,"Tlemcen","ville d'art à l'extrême ouest, ancienne capitale royale."],
    [14,"Tiaret","sur les Hauts Plateaux de l'Ouest."],
    [15,"Tizi Ouzou","cœur de la Kabylie — ferme les 15 wilayas d'origine de 1963."],
    [16,"Alger","la capitale ouvre le bloc ajouté en 1974."],
    [17,"Djelfa","porte des Hauts Plateaux, juste après Alger."],
    [18,"Jijel","petite wilaya côtière de l'Est, ses criques et ses forêts."],
    [19,"Sétif","hauts plateaux de l'Est, grande ville universitaire."],
    [20,"Saïda","à l'ouest, chiffre rond pour une wilaya discrète."],
    [21,"Skikda","port industriel de l'Est."],
    [22,"Sidi Bel Abbès","à l'ouest, ancienne ville de garnison."],
    [23,"Annaba","tout à l'est sur la côte, ville de Saint Augustin."],
    [24,"Guelma","voisine d'Annaba, à l'intérieur des terres."],
    [25,"Constantine","la ville des ponts suspendus — un quart de siècle pour la capitale de l'Est."],
    [26,"Médéa","au sud d'Alger, dans l'Atlas blidéen."],
    [27,"Mostaganem","port de l'Ouest, réputée pour ses plages."],
    [28,"M'Sila","au centre du pays, entre Tell et Hauts Plateaux."],
    [29,"Mascara","à l'ouest, ville natale de l'Émir Abdelkader."],
    [30,"Ouargla","grande wilaya saharienne, capitale pétrolière du Sud."],
    [31,"Oran","la deuxième ville du pays ferme le bloc de 1974, juste avant l'ordre alphabétique de 1984."],
    [32,"El Bayadh","ouvre l'ère alphabétique arabe (1984), à l'ouest saharien."],
    [33,"Illizi","tout au sud-est, aux portes du Tassili."],
    [34,"Bordj Bou Arréridj","hauts plateaux de l'Est, entre Sétif et Bouira."],
    [35,"Boumerdès","juste à côté d'Alger, sur la côte."],
    [36,"El Tarf","extrémité nord-est du pays — \"tarf\" veut dire extrémité en arabe."],
    [37,"Tindouf","tout à l'ouest du grand Sud, la plus isolée."],
    [38,"Tissemsilt","petite wilaya des Hauts Plateaux de l'Ouest."],
    [39,"El Oued","la ville aux mille coupoles, Sahara nord-est."],
    [40,"Khenchela","dans les Aurès, au sud de Batna."],
    [41,"Souk Ahras","ville natale de Saint Augustin, frontière tunisienne."],
    [42,"Tipaza","la côte antique et ses ruines romaines, à l'ouest d'Alger."],
    [43,"Mila","petite wilaya de l'Est, entre Constantine et Jijel."],
    [44,"Aïn Defla","à l'ouest d'Alger, dans la vallée du Chélif."],
    [45,"Naâma","extrême ouest saharien, frontière marocaine."],
    [46,"Aïn Témouchent","côte ouest, entre Oran et Tlemcen."],
    [47,"Ghardaïa","la vallée du Mzab et ses cités ocre — avant-dernier code du bloc 1984."],
    [48,"Relizane","dernier code des wilayas historiques, dans la plaine du Chélif à l'ouest."],

    /* 49–58 : les 10 wilayas créées en 2019, chacune détachée d'une
       wilaya historique déjà connue — c'est ce lien qui sert de repère,
       pas un ordre alphabétique ou géographique (il n'y en a pas). */
    [49,"Timimoun","la « ville rouge » du Gourara, détachée d'Adrar — premier code du bloc de 2019."],
    [50,"Bordj Badji Mokhtar","à l'extrême sud-ouest, frontière malienne — comme Timimoun, détachée d'Adrar."],
    [51,"Ouled Djellal","dans la plaine au nord de Biskra, dont elle est détachée."],
    [52,"Béni Abbès","oasis de la Saoura, détachée de Béchar."],
    [53,"In Salah","au cœur du Sahara (le Tidikelt), détachée de Tamanrasset — l'une des villes les plus chaudes du pays."],
    [54,"In Guezzam","tout au sud, frontière nigérienne — comme In Salah, détachée de Tamanrasset."],
    [55,"Touggourt","grande oasis dattière de l'Oued Righ, détachée d'Ouargla."],
    [56,"Djanet","porte du Tassili n'Ajjer, à l'extrême sud-est, détachée d'Illizi."],
    [57,"El M'Ghaier","dans l'Oued Righ comme Touggourt, mais détachée d'El Oued."],
    [58,"El Meniaa","l'ancienne El Goléa, sur la route du grand Sud, détachée de Ghardaïa — dernier code du bloc de 2019."],

    /* 59–69 : les 11 wilayas des Hauts Plateaux créées en 2025, même
       principe — chacune détachée d'une wilaya du Tell déjà connue. */
    [59,"Aflou","hauts plateaux frais du Djebel Amour, détachée de Laghouat — premier code du bloc de 2025."],
    [60,"Barika","dans la plaine à l'ouest de Batna, dont elle est détachée."],
    [61,"El Kantara","la gorge qui sépare le Tell du Sahara, détachée de Biskra."],
    [62,"Bir El Ater","région minière de l'Est (phosphates du Djebel Onk), détachée de Tébessa."],
    [63,"El Aricha","hauts plateaux de l'Ouest, frontière marocaine, détachée de Tlemcen."],
    [64,"Ksar Chellala","hauts plateaux de l'Ouest, détachée de Tiaret."],
    [65,"Aïn Oussara","sur la route Alger–Sud, détachée de Djelfa."],
    [66,"Messaad","comme Aïn Oussara, détachée de Djelfa — les deux se suivent."],
    [67,"Ksar El Boukhari","au sud de Médéa, dont elle est détachée."],
    [68,"Bou Saâda","la « ville du bonheur » aux portes du Sahara, détachée de M'Sila."],
    [69,"El Abiodh Sidi Cheikh","zaouïa historique de l'Ouest saharien, détachée d'El Bayadh — dernier code du pays."]
  ];

  var REGION_COLOR = {
    "Centre":"var(--accent)", "Est":"var(--teal)", "Ouest":"var(--slate)",
    "Sud":"var(--olive)", "Hauts Plateaux":"var(--rose)"
  };

  